cloud:
  aws:
    credentials:
      access-key: AKIAZTJ2QLZ4DLMTMUP2
      secret-key: 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
    region:
      static: US East (N. Virginia) us-east-1
    stack:
      auto: false

application:
  bucket:
    name: trackerhub


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

spring.data.mongodb:
  database: Tracker_Hub # Database name.
  uri: mongodb+srv://Tracker_Hub:E9xJHdUVmRrmw3B3@tracker-hub.v6odbn0.mongodb.net/?retryWrites=true&w=majority # Mongo database URI. Cannot be set with host, port and credentials.

server:
  port: 9092

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: email-address
    password: email-password
    port: '587'